@host=http://localhost:5194

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName" : "Amichai",
  "LastName": "Mantinband",
  "email": "amichai@mantinband.com",
  "password": "Amiko1232!"
}
